;;; init.el --- Emacs initialization file -*- lexical-binding: t -*-

;; Copyright (C) 2025 Thomas Freeman

;; Author: Thomas Freeman
;; Maintainer: Thomas Freeman
;; Keywords: lisp
;; Created: 02 Feb 2025

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is an init file for Emacs.
;; This file is NOT a part of Emacs.
;; This file IS NOT intended to be edited! It was generated by init.org.
;; For code comments, see init.org.

;;; URL: https://github.com/tfree87/.emacs.d

;; For documentation and for editing this file, see init.org in the
;; github repository tfree87/.emacs.d
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Code:


;; Speed up Emacs loading during initialization.
(let ((file-name-handler-alist nil))

  ;; Load custom file from customize interface

  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
  
  (let ((default-directory "~/.emacs.d/modules/"))
    (normal-top-level-add-subdirs-to-load-path))

  ;; Add package repositories
  (require 'package)
  (add-to-list 'package-archives
               '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
  
  ;; Start benchmarking and garbage collector early
  
  (require 'freemacs-benchmark-init)
  (require 'freemacs-gcmh)
  
  ;; Load modules from modules directory.
  ;;;; Correct ordering is critical.

  (require 'freemacs-elisp)
  (require 'freemacs-portable)
  (require 'freemacs-no-littering)
  (require 'freemacs-trapt)
  (require 'freemacs-auctex)
  (require 'freemacs-aggressive-indent)
  (require 'freemacs-autohotkey)
  ;;(require 'freemacs-bleachbit)
  (require 'freemacs-calfw)
  (require 'freemacs-c-mode)
  (require 'freemacs-cape)
  (require 'freemacs-clemav)
  (require 'freemacs-consult)
  (require 'freemacs-corfu)
  (require 'freemacs-completion-preview)
  (require 'freemacs-dired)
  (require 'freemacs-drsync)
  (require 'freemacs-docker)
  (require 'freemacs-defaults)
  (require 'freemacs-eat)
  (require 'freemacs-electric-pair)
  (require 'freemacs-elfeed)
  (require 'freemacs-elfeed-protocol)
  (require 'freemacs-embark)
  (require 'freemacs-eshell)
  (require 'freemacs-app-launcher)
  (require 'freemacs-fireplace)
  ;;(require 'freemacs-firewalld)
  (require 'freemacs-fotd)
  (require 'freemacs-flymake)
  (require 'freemacs-gnuplot)
  (require 'freemacs-gnus)
  (require 'freemacs-go)
  (require 'freemacs-helpful)
  (require 'freemacs-ibuffer)
  (require 'freemacs-imenu)
  (require 'freemacs-indent-bars)
  (require 'freemacs-jinx)
  (require 'freemacs-ledger)
  (require 'freemacs-magit)
  (require 'freemacs-marginalia)
  (require 'freemacs-markdown)
  (require 'freemacs-meow)
  (require 'freemacs-multi-vterm)
  (require 'freemacs-mp)
  (require 'freemacs-nerd-icons)
  (require 'freemacs-nyan)
  (require 'freemacs-orderless)
  (require 'freemacs-org)
  (require 'freemacs-org-contacts)
  (require 'freemacs-org-mime)
  (require 'freemacs-minimap)
  (require 'freemacs-org-mm)
  (require 'freemacs-org-ql)
  (require 'freemacs-orgsl)
  (require 'freemacs-ox-publish)
  (require 'freemacs-package-lint)
  (require 'freemacs-paren)
  (require 'freemacs-pdf)
  (require 'freemacs-popper)
  (require 'freemacs-plantuml)
  (require 'freemacs-prog-mode)
  (require 'freemacs-recentf)
  (require 'freemacs-rainbow-delimiters)
  (require 'freemacs-rh)
  (require 'freemacs-savehist)
  (require 'freemacs-shelly)
  (require 'freemacs-sly)
  (require 'freemacs-speed-type)
  (require 'freemacs-topsy)
  (require 'freemacs-trashed)
  (require 'freemacs-vertico)
  (require 'freemacs-vterm)
  (require 'freemacs-theme)
  (require 'freemacs-sp)
  ;;(require 'freemacs-spellcheck)
  ;;(require 'freemacs-wk)
  (require 'freemacs-winner)
  (require 'freemacs-yasnippet)
  (require 'freemacs-gif-screencast)
  (require 'freemacs-server))

;;; init.el ends here
